#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Illuminate\Container\Container;
use Illuminate\Events\Dispatcher;
use Illuminate\Console\Application;



$container = new Container;
$events = new Dispatcher($container);

$artisan = new Application($container, $events, 'Version 1');
$artisan->setName('Php Portfolio App');

// Bind commands

$artisan->resolve(UserCommand::class);

$artisan->resolve(BlogsTableCommand::class);

$artisan->resolve(SettingsTableCommand::class);

$artisan->resolve(PortfolioTableCommand::class);

$artisan->resolve(ServicesTableCommand::class);

$artisan->resolve(TestimonialTableCommand::class);

$artisan->resolve(Migrate::class);

$artisan->run();