#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Commands\Db_tables_Commands\BlogsTableCommand;
use Commands\Db_tables_Commands\PortfolioTableCommand;
use Commands\Db_tables_Commands\ServicesTableCommand;
use Commands\Db_tables_Commands\SettingsTableCommand;
use Commands\Db_tables_Commands\TestimonialTableCommand;
use Commands\Db_tables_Commands\UserCommand;
use Commands\MakeControllerCommand;
use Commands\Migrate;
use Illuminate\Container\Container;
use Illuminate\Events\Dispatcher;
use Illuminate\Console\Application;

$container = new Container;

$events = new Dispatcher($container);

$artisan = new Application($container, $events, 'Version 1');
$artisan->setName('Php Portfolio App');

$artisan->resolve(UserCommand::class);

$artisan->resolve(BlogsTableCommand::class);

$artisan->resolve(SettingsTableCommand::class);

$artisan->resolve(PortfolioTableCommand::class);

$artisan->resolve(ServicesTableCommand::class);

$artisan->resolve(TestimonialTableCommand::class);

$artisan->resolve(Migrate::class);

$artisan->resolve(MakeControllerCommand::class);

$artisan->run();